name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi ${{ github.actor }} thanks for adding this issue, I will see to it that I respond to you asap'
        pr-message: "Thank you for this first pull request, I hope this won't be the last :smile:"
